// ============================================================
// CODEMAP — Concept Data
// Every concept: history, definition, analogy, code, application
// ============================================================

const TIERS = [
  { id: 0, name: "Foundations", color: "#5EEAD4" },
  { id: 1, name: "Basics", color: "#5EEAD4" },
  { id: 2, name: "Control Flow", color: "#67E8F9" },
  { id: 3, name: "Data Structures I", color: "#7DD3FC" },
  { id: 4, name: "Functions", color: "#93C5FD" },
  { id: 5, name: "Object-Oriented Programming", color: "#A5B4FC" },
  { id: 6, name: "Data Structures & Algorithms", color: "#C4B5FD" },
  { id: 7, name: "Advanced Concepts", color: "#F0ABFC" },
  { id: 8, name: "Systems & Applied", color: "#F9A8D4" },
  { id: 9, name: "Specialization Bridges", color: "#FCA5A5" },
];

const CONCEPTS = [
// ---------------- TIER 0 — FOUNDATIONS ----------------
{
  id: "history-of-programming", tier: 0, title: "History of Programming",
  difficulty: "Foundation", viz: "timeline",
  history: "It began in 1843, when Ada Lovelace wrote the first published algorithm meant for a machine — Charles Babbage's unbuilt Analytical Engine. A century later, Assembly language let humans write CPU instructions in words instead of raw binary. FORTRAN (1957) and COBOL (1959) brought human-readable syntax. C (1972) gave low-level control with high-level structure. Python, Java, and JavaScript then made programming accessible to millions.",
  definition: "Programming is the act of writing precise instructions that a computer can execute, using a language that sits somewhere between human thought and machine electricity.",
  analogy: "Like writing a recipe so exact that even someone who has never cooked — and never will improvise — can follow it perfectly.",
  code: { c: "// 1972: C compiles to raw machine instructions\n#include <stdio.h>\nint main() {\n  printf(\"Hello, 1972!\\n\");\n  return 0;\n}", python: "# 1991: Python favors readability\nprint(\"Hello, readability!\")", javascript: "// 1995: JavaScript brought code to the browser\nconsole.log(\"Hello, web!\");" },
  application: "Every app on your phone, every website, every ATM and traffic light runs on a chain of language evolution that starts here.",
},
{
  id: "compilers-interpreters", tier: 0, title: "Compilers vs Interpreters",
  difficulty: "Foundation", viz: "pipeline",
  history: "Grace Hopper built the first compiler (A-0) in 1952, because writing machine code by hand for every task was too slow and error-prone. Interpreters emerged alongside early Lisp and BASIC systems, trading raw speed for the ability to run code immediately, line by line.",
  definition: "A compiler translates your entire program into machine code before running it. An interpreter reads and executes your code line by line, on the fly.",
  analogy: "A compiler is like translating a whole book into another language before handing it over. An interpreter is like a live interpreter translating a speech sentence by sentence as it's spoken.",
  code: { c: "// Compiled: gcc program.c -o program\n// Then run: ./program", python: "# Interpreted: python program.py\n# Runs line-by-line immediately", javascript: "// JIT-compiled by V8 at runtime\n// (hybrid of both worlds)" },
  application: "C/C++ compile to fast native apps and game engines. Python/JS interpret for quick iteration — ideal for scripting, web apps, and data science.",
},
{
  id: "how-code-runs", tier: 0, title: "How Code Becomes Execution",
  difficulty: "Foundation", viz: "pipeline",
  history: "Von Neumann's 1945 architecture — one memory holding both instructions and data — became the blueprint nearly every computer still follows today.",
  definition: "Source code is translated into machine instructions (0s and 1s), loaded into memory, and executed one instruction at a time by the CPU.",
  analogy: "Like sheet music (source code) being read and played note-by-note by a musician (the CPU), using their memorized technique (machine instructions).",
  code: { c: "int x = 5;\n// becomes something like:\n// MOV eax, 5\n// MOV [x], eax", python: "x = 5\n# CPython compiles this to\n# bytecode, then interprets it", javascript: "let x = 5;\n// V8 parses -> bytecode -> \n// optimized machine code" },
  application: "Understanding this pipeline is why performance tuning, debugging crashes, and reading assembly output all become possible.",
},
{
  id: "flowcharts-pseudocode", tier: 0, title: "Flowcharts & Pseudocode",
  difficulty: "Foundation", viz: "flowchart",
  history: "Flowcharting standards were formalized by ANSI in the 1960s so that engineers across companies could read each other's program logic without knowing the target language.",
  definition: "A flowchart is a diagram of a process using standard shapes (oval = start/end, rectangle = process, diamond = decision). Pseudocode is plain-English, structured logic that isn't tied to any real language's syntax.",
  analogy: "Both are blueprints — you plan the house on paper before laying a single brick.",
  code: { c: "// Pseudocode:\n// START\n// IF age >= 18 THEN print \"Adult\"\n// ELSE print \"Minor\"\n// END", python: "# Same logic, real Python:\nif age >= 18:\n    print(\"Adult\")\nelse:\n    print(\"Minor\")", javascript: "// Same logic, real JS:\nif (age >= 18) console.log(\"Adult\");\nelse console.log(\"Minor\");" },
  application: "Used in technical interviews, system design docs, and to plan logic before writing a single line of real code.",
},

// ---------------- TIER 1 — BASICS ----------------
{
  id: "variables", tier: 1, title: "Variables & Data Types",
  difficulty: "Easy", viz: "memory-boxes",
  history: "Early machine code had no named variables — only raw memory addresses. FORTRAN (1957) introduced named variables, letting programmers write 'x' instead of memorizing address 0x3F2A.",
  definition: "A variable is a named container in memory that holds a value, which can change while the program runs. A data type defines what kind of value it can hold (integer, decimal, text, boolean).",
  analogy: "A variable is a labeled box on a shelf. The label doesn't change, but what's inside the box can be swapped out.",
  code: { c: "int age = 20;\nfloat price = 99.5;\nchar grade = 'A';", python: "age = 20\nprice = 99.5\nname = \"Jay\"", javascript: "let age = 20;\nconst price = 99.5;\nlet name = \"Jay\";" },
  application: "Every app state — your cart total, your login status, a game's score — lives in variables.",
},
{
  id: "operators", tier: 1, title: "Operators",
  difficulty: "Easy", viz: "operators",
  history: "Operator symbols (+, -, *, /) were borrowed directly from centuries-old mathematical notation to make early languages feel familiar to scientists and engineers.",
  definition: "Operators perform actions on values: arithmetic (+ - * / %), relational (== > < !=), logical (&& || !), and bitwise (& | ^ << >>).",
  analogy: "Operators are verbs in the sentence of your code — they make things happen to your variables.",
  code: { c: "int sum = 5 + 3;      // arithmetic\nint isEqual = (5 == 5); // relational\nint result = (1 && 0);  // logical", python: "total = 5 + 3\nis_equal = (5 == 5)\nresult = (True and False)", javascript: "let total = 5 + 3;\nlet isEqual = (5 === 5);\nlet result = (true && false);" },
  application: "Powers everything from calculating a shopping cart total to validating a login form.",
},
{
  id: "io-basics", tier: 1, title: "Input / Output",
  difficulty: "Easy", viz: "io-flow",
  history: "Early computers took input via punch cards and gave output on printouts. Interactive I/O (typing and seeing results instantly) only became standard with terminals in the 1970s.",
  definition: "Input is data a program receives (keyboard, file, sensor). Output is what the program produces (screen, file, speaker).",
  analogy: "Like a conversation — input is what someone says to you, output is your reply.",
  code: { c: "int x;\nscanf(\"%d\", &x);\nprintf(\"You entered %d\\n\", x);", python: "x = input(\"Enter a number: \")\nprint(f\"You entered {x}\")", javascript: "let x = prompt(\"Enter a number:\");\nconsole.log(`You entered ${x}`);" },
  application: "Every form, chatbot, voice assistant, and sensor reading is an input/output loop at its core.",
},
{
  id: "comments-readability", tier: 1, title: "Comments & Readability",
  difficulty: "Easy", viz: "readability",
  history: "As codebases grew from hundreds to millions of lines in the 1970s–80s, teams realized code is read far more often than it's written — comments became essential for collaboration.",
  definition: "Comments are notes in code ignored by the computer but read by humans, explaining why code does what it does.",
  analogy: "Margin notes in a textbook — the exam doesn't grade them, but they help the next reader (including future-you) understand faster.",
  code: { c: "// Calculate area of a circle\nfloat area = 3.14 * r * r;", python: "# Calculate area of a circle\narea = 3.14 * r ** 2", javascript: "// Calculate area of a circle\nlet area = 3.14 * r * r;" },
  application: "Critical in team projects, open-source libraries, and any code you'll revisit months later.",
},
{
  id: "type-conversion", tier: 1, title: "Type Conversion / Casting",
  difficulty: "Easy", viz: "type-cast",
  history: "As languages mixed integers, floats, and text more freely, automatic ('implicit') and manual ('explicit') conversion rules were designed to avoid silent bugs from mismatched types.",
  definition: "Converting a value from one data type to another — implicitly (automatic) or explicitly (you request it).",
  analogy: "Like converting currency before a purchase — the value is the same idea, but the format has to match what's accepted.",
  code: { c: "int x = 10;\nfloat y = (float)x; // explicit cast", python: "x = \"10\"\ny = int(x)  # explicit conversion", javascript: "let x = \"10\";\nlet y = Number(x); // explicit\nlet z = \"5\" + 3;   // implicit -> \"53\"" },
  application: "Essential when reading user input (always text) and converting it into numbers for calculations.",
},
{
  id: "constants", tier: 1, title: "Constants",
  difficulty: "Easy", viz: "memory-boxes",
  history: "As programs grew, hard-coded 'magic numbers' scattered everywhere made bugs hard to trace. Constants let one named, unchangeable value be defined once and reused safely.",
  definition: "A constant is a named value that cannot be changed after it's set.",
  analogy: "A physical constant like π — its value never changes no matter where in the universe you use it.",
  code: { c: "#define PI 3.14159\nconst int MAX_USERS = 100;", python: "PI = 3.14159  # convention: uppercase\nMAX_USERS = 100", javascript: "const PI = 3.14159;\nconst MAX_USERS = 100;" },
  application: "Used for configuration values, physical/math constants, and API keys that must never accidentally change.",
},

// ---------------- TIER 2 — CONTROL FLOW ----------------
{
  id: "if-else", tier: 2, title: "If-Else / Switch-Case",
  difficulty: "Easy", viz: "branch",
  history: "Conditional branching is as old as computing itself — the 1949 EDSAC machine already supported 'jump if condition' instructions, the ancestor of every if-statement today.",
  definition: "Conditional statements let a program choose which block of code to run based on whether a condition is true or false.",
  analogy: "A fork in the road — you check a sign (the condition) before deciding which path to take.",
  code: { c: "if (age >= 18) {\n  printf(\"Adult\");\n} else {\n  printf(\"Minor\");\n}", python: "if age >= 18:\n    print(\"Adult\")\nelse:\n    print(\"Minor\")", javascript: "if (age >= 18) {\n  console.log(\"Adult\");\n} else {\n  console.log(\"Minor\");\n}" },
  application: "Login checks, game logic, form validation — any decision-making in software uses this.",
},
{
  id: "loops", tier: 2, title: "Loops (for, while, do-while)",
  difficulty: "Easy", viz: "loop-counter",
  history: "Loops replaced the painful alternative — copy-pasting the same instruction hundreds of times — and were among the very first control structures in FORTRAN.",
  definition: "A loop repeats a block of code multiple times, either a fixed number of times (for) or until a condition changes (while).",
  analogy: "Like doing laps on a track — you keep going around until you've done the set number of laps, or until you decide to stop.",
  code: { c: "for (int i = 0; i < 5; i++) {\n  printf(\"%d\\n\", i);\n}", python: "for i in range(5):\n    print(i)", javascript: "for (let i = 0; i < 5; i++) {\n  console.log(i);\n}" },
  application: "Processing every item in a list, animating frames, retrying a network request — loops are everywhere.",
},
{
  id: "break-continue", tier: 2, title: "Break & Continue",
  difficulty: "Easy", viz: "loop-counter",
  history: "Introduced so programmers could exit or skip loop iterations without the messy, error-prone 'goto' jumps common in early code.",
  definition: "'break' exits a loop immediately. 'continue' skips the rest of the current iteration and moves to the next one.",
  analogy: "Break is like leaving a queue entirely. Continue is like stepping out, then re-joining at the back for the next round.",
  code: { c: "for (int i = 0; i < 10; i++) {\n  if (i == 5) break;\n  if (i % 2 == 0) continue;\n  printf(\"%d \", i);\n}", python: "for i in range(10):\n    if i == 5:\n        break\n    if i % 2 == 0:\n        continue\n    print(i)", javascript: "for (let i = 0; i < 10; i++) {\n  if (i === 5) break;\n  if (i % 2 === 0) continue;\n  console.log(i);\n}" },
  application: "Searching a list and stopping early once found; skipping invalid entries while processing data.",
},
{
  id: "nested-loops", tier: 2, title: "Nested Loops",
  difficulty: "Medium", viz: "grid",
  history: "As programs began handling grids and tables (spreadsheets, images, matrices), nesting loops inside loops became the natural way to walk through two dimensions.",
  definition: "A loop placed inside another loop — the inner loop completes fully for every single iteration of the outer loop.",
  analogy: "Like reading a book: the outer loop moves page by page, the inner loop moves line by line on each page.",
  code: { c: "for (int i = 0; i < 3; i++)\n  for (int j = 0; j < 3; j++)\n    printf(\"(%d,%d) \", i, j);", python: "for i in range(3):\n    for j in range(3):\n        print(f\"({i},{j})\", end=\" \")", javascript: "for (let i = 0; i < 3; i++)\n  for (let j = 0; j < 3; j++)\n    console.log(`(${i},${j})`);" },
  application: "Rendering pixel grids, multiplication tables, and comparing every pair of items in two lists.",
},
{
  id: "recursion-intro", tier: 2, title: "Recursion (Introduction)",
  difficulty: "Medium", viz: "call-stack",
  history: "Rooted in 1930s mathematical logic (Church, Turing), recursion entered programming through Lisp in 1958 — a function calling itself was a radical idea at the time.",
  definition: "A function that calls itself to solve a smaller version of the same problem, until it reaches a 'base case' that stops the calls.",
  analogy: "Russian nesting dolls — each doll (call) contains a smaller one, until you reach the tiniest doll that doesn't open further (the base case).",
  code: { c: "int factorial(int n) {\n  if (n == 0) return 1; // base case\n  return n * factorial(n - 1);\n}", python: "def factorial(n):\n    if n == 0:\n        return 1\n    return n * factorial(n - 1)", javascript: "function factorial(n) {\n  if (n === 0) return 1;\n  return n * factorial(n - 1);\n}" },
  application: "Used in file-system traversal, parsing nested data (JSON), and tree/graph algorithms.",
},

// ---------------- TIER 3 — DATA STRUCTURES I ----------------
{
  id: "arrays", tier: 3, title: "Arrays",
  difficulty: "Medium", viz: "array-boxes",
  history: "Arrays trace back to FORTRAN (1957), designed to store scientific data — like a table of measurements — in one contiguous block of memory for fast access.",
  definition: "A fixed-size collection of elements of the same type, stored in contiguous memory, accessed by an index starting at 0.",
  analogy: "A row of numbered lockers — you can jump straight to locker #7 without opening the first six.",
  code: { c: "int nums[5] = {10, 20, 30, 40, 50};\nprintf(\"%d\", nums[2]); // 30", python: "nums = [10, 20, 30, 40, 50]\nprint(nums[2])  # 30", javascript: "let nums = [10, 20, 30, 40, 50];\nconsole.log(nums[2]); // 30" },
  application: "Storing pixel data in images, leaderboard scores, or any ordered list of same-type items.",
},
{
  id: "strings", tier: 3, title: "Strings",
  difficulty: "Medium", viz: "array-boxes",
  history: "In C, a string is just an array of characters ending in a special '\\0' marker — a low-level design choice. Later languages like Python made strings a true, safer built-in type.",
  definition: "A sequence of characters representing text, usually treated as an array of characters under the hood.",
  analogy: "A string of beads, where each bead is one character, read in order to form a word.",
  code: { c: "char name[] = \"Jay\";\nprintf(\"%c\", name[0]); // 'J'", python: "name = \"Jay\"\nprint(name[0])  # 'J'\nprint(name.upper())  # 'JAY'", javascript: "let name = \"Jay\";\nconsole.log(name[0]); // 'J'\nconsole.log(name.toUpperCase());" },
  application: "Every username, message, search query, and file name your programs handle.",
},
{
  id: "structures", tier: 3, title: "Structures / Records",
  difficulty: "Medium", viz: "struct-box",
  history: "Introduced in C to group related but different-typed data (like a name and an age) under one label, before object-oriented programming existed.",
  definition: "A custom data type that bundles multiple related variables (possibly of different types) together under one name.",
  analogy: "A student's ID card — one card holding a name (text), roll number (integer), and photo (data) together.",
  code: { c: "struct Student {\n  char name[20];\n  int age;\n};\nstruct Student s1 = {\"Jay\", 20};", python: "# Python uses classes or dicts\nstudent = {\"name\": \"Jay\", \"age\": 20}", javascript: "let student = { name: \"Jay\", age: 20 };" },
  application: "Representing real-world entities: a student record, a product in an e-commerce catalog, a GPS coordinate.",
},
{
  id: "pointers", tier: 3, title: "Pointers / References",
  difficulty: "Hard", viz: "pointer-arrow",
  history: "C (1972) exposed pointers directly to give programmers raw control over memory — powerful, but the source of countless historical bugs and security vulnerabilities.",
  definition: "A pointer stores the memory address of another variable, rather than a value itself. Many modern languages hide this as 'references'.",
  analogy: "A pointer is like a house address written on a piece of paper — it doesn't contain the house itself, just directions to find it.",
  code: { c: "int x = 10;\nint *p = &x;   // p holds address of x\nprintf(\"%d\", *p); // dereference: 10", python: "# Python uses references implicitly\na = [1, 2, 3]\nb = a  # b references the same list", javascript: "let a = [1, 2, 3];\nlet b = a; // b references same array" },
  application: "Enables efficient memory use in operating systems, linked lists, and passing large data without copying it.",
},

// ---------------- TIER 4 — FUNCTIONS ----------------
{
  id: "functions", tier: 4, title: "Functions / Methods",
  difficulty: "Medium", viz: "function-box",
  history: "Subroutines appeared as early as 1945 in Von Neumann's plans, so common blocks of logic could be written once and reused, rather than duplicated everywhere.",
  definition: "A named, reusable block of code that performs a task, optionally takes inputs (parameters), and optionally returns a result.",
  analogy: "A vending machine — you insert coins (parameters), it performs its internal process, and returns a snack (the result).",
  code: { c: "int add(int a, int b) {\n  return a + b;\n}\nint sum = add(3, 4); // 7", python: "def add(a, b):\n    return a + b\n\nsum_result = add(3, 4)  # 7", javascript: "function add(a, b) {\n  return a + b;\n}\nlet sum = add(3, 4); // 7" },
  application: "Every reusable piece of logic in software — from a single calculation to an entire payment-processing routine.",
},
{
  id: "scope", tier: 4, title: "Scope (Local & Global)",
  difficulty: "Medium", viz: "scope-boxes",
  history: "As programs grew larger, uncontrolled global variables caused conflicts between different parts of a program — scope rules were introduced to contain variables to where they're needed.",
  definition: "Scope defines where a variable can be accessed. Local variables exist only inside the function they're declared in; global variables are accessible everywhere.",
  analogy: "A local variable is a conversation inside a closed room — only people in that room hear it. A global variable is an announcement over a loudspeaker — everyone hears it.",
  code: { c: "int globalX = 100;\nvoid demo() {\n  int localY = 5; // only exists here\n}", python: "global_x = 100\n\ndef demo():\n    local_y = 5  # only exists here", javascript: "let globalX = 100;\nfunction demo() {\n  let localY = 5; // only exists here\n}" },
  application: "Prevents naming conflicts and accidental data corruption across different parts of a large codebase.",
},
{
  id: "function-overloading", tier: 4, title: "Function Overloading",
  difficulty: "Medium", viz: "function-box",
  history: "Introduced in languages like C++ (1980s) to let a single function name behave differently depending on the type or number of arguments passed.",
  definition: "Defining multiple functions with the same name but different parameter types or counts, so the right one is chosen automatically.",
  analogy: "A single word that means different things in different contexts — the listener figures out which meaning fits from the situation.",
  code: { c: "// C doesn't support this natively —\n// C++ does:\nint add(int a, int b) { return a+b; }\nfloat add(float a, float b) { return a+b; }", python: "# Python instead uses default args\n# or *args for flexible functions\ndef add(a, b=0):\n    return a + b", javascript: "// JS handles this via flexible args\nfunction add(...nums) {\n  return nums.reduce((a,b) => a+b, 0);\n}" },
  application: "Common in strongly-typed languages like Java/C++ for math libraries and constructors handling multiple input types.",
},
{
  id: "modules-packages", tier: 4, title: "Modules, Packages & Libraries",
  difficulty: "Medium", viz: "modules",
  history: "As software projects outgrew a single file, languages introduced ways to split code across files and share reusable code — giving rise to today's package ecosystems (npm, PyPI).",
  definition: "A module is a file of reusable code. A package/library bundles related modules so others can import and use them without rewriting the logic.",
  analogy: "Buying pre-made furniture instead of cutting your own wood — someone already solved the problem, you just 'import' the solution.",
  code: { c: "#include <math.h>\ndouble r = sqrt(16.0); // 4.0", python: "import math\nr = math.sqrt(16)  # 4.0", javascript: "import { sqrt } from 'mathjs';\nlet r = sqrt(16); // 4" },
  application: "Nearly every real project relies on libraries — from UI frameworks like React to ML libraries like TensorFlow.",
},

// ---------------- TIER 5 — OOP ----------------
{
  id: "classes-objects", tier: 5, title: "Classes & Objects",
  difficulty: "Medium", viz: "class-diagram",
  history: "Simula (1967) introduced classes and objects for simulating real-world systems. Smalltalk (1972) then built an entire language philosophy around 'everything is an object'.",
  definition: "A class is a blueprint defining properties and behaviors. An object is a specific instance created from that blueprint.",
  analogy: "A class is a cookie cutter; an object is each individual cookie made from it — same shape, different toppings (data).",
  code: { c: "// C has no classes — use structs + functions", python: "class Car:\n    def __init__(self, brand):\n        self.brand = brand\n\nmy_car = Car(\"Toyota\")", javascript: "class Car {\n  constructor(brand) {\n    this.brand = brand;\n  }\n}\nlet myCar = new Car(\"Toyota\");" },
  application: "Nearly all modern software — games, apps, simulations — is modeled as interacting objects.",
},
{
  id: "encapsulation", tier: 5, title: "Encapsulation",
  difficulty: "Medium", viz: "class-diagram",
  history: "A core pillar of OOP from Simula and Smalltalk onward, designed to prevent one part of a large program from accidentally corrupting another part's internal data.",
  definition: "Bundling data and the methods that operate on it together, while hiding internal details from outside interference — usually via private fields and public methods.",
  analogy: "A car's engine is encapsulated under the hood — you interact through the steering wheel and pedals, not by touching the engine directly.",
  code: { c: "// Not native to C", python: "class Account:\n    def __init__(self):\n        self.__balance = 0  # private\n    def deposit(self, amt):\n        self.__balance += amt", javascript: "class Account {\n  #balance = 0; // private field\n  deposit(amt) { this.#balance += amt; }\n}" },
  application: "Protects sensitive data like bank balances or passwords from being changed directly from outside the class.",
},
{
  id: "inheritance", tier: 5, title: "Inheritance",
  difficulty: "Medium", viz: "tree-diagram",
  history: "Simula introduced inheritance in 1967 to let programmers reuse and extend existing simulation classes, instead of rewriting shared logic each time.",
  definition: "A mechanism where a new class (child) reuses properties and behaviors of an existing class (parent), and can add or override its own.",
  analogy: "A child inheriting traits from a parent, but also developing their own unique personality on top of them.",
  code: { c: "// Not native to C", python: "class Animal:\n    def speak(self):\n        print(\"...\")\n\nclass Dog(Animal):\n    def speak(self):\n        print(\"Woof!\")", javascript: "class Animal {\n  speak() { console.log(\"...\"); }\n}\nclass Dog extends Animal {\n  speak() { console.log(\"Woof!\"); }\n}" },
  application: "UI frameworks build specialized components (Button, Checkbox) from a shared base Component class.",
},
{
  id: "polymorphism", tier: 5, title: "Polymorphism",
  difficulty: "Medium", viz: "class-diagram",
  history: "From the Greek for 'many forms', this OOP pillar formalized an idea already emerging in Simula: the same interface can be used to trigger different behavior depending on the actual object.",
  definition: "The ability of different classes to be treated through a common interface, while each responds to the same call in its own way.",
  analogy: "Pressing 'play' means something different on a music app versus a video app — same action, different behavior per context.",
  code: { c: "// Not native to C", python: "for animal in [Dog(), Cat()]:\n    animal.speak()  # each responds differently", javascript: "[new Dog(), new Cat()].forEach(a => a.speak());" },
  application: "Game engines call `.update()` on every game object — players, enemies, items — and each responds differently.",
},
{
  id: "abstraction", tier: 5, title: "Abstraction",
  difficulty: "Medium", viz: "class-diagram",
  history: "Formalized alongside the other OOP pillars, abstraction lets programmers manage growing system complexity by hiding unnecessary detail behind simple interfaces.",
  definition: "Showing only essential features of an object while hiding complex internal implementation details.",
  analogy: "Driving a car by using the steering wheel and pedals, without needing to understand combustion engineering underneath.",
  code: { c: "// Not native to C", python: "from abc import ABC, abstractmethod\nclass Shape(ABC):\n    @abstractmethod\n    def area(self): pass", javascript: "class Shape {\n  area() { throw new Error(\"Implement me\"); }\n}" },
  application: "APIs are abstraction in action — you call `fetch()` without knowing how networking is implemented underneath.",
},
{
  id: "constructors", tier: 5, title: "Constructors & Destructors",
  difficulty: "Medium", viz: "class-diagram",
  history: "Introduced so that objects are automatically set up correctly the moment they're created, instead of requiring a separate manual setup step every time.",
  definition: "A constructor runs automatically when an object is created, to initialize its data. A destructor runs when an object is destroyed, to clean up resources.",
  analogy: "A constructor is like checking into a hotel room — the essentials (towels, keys) are set up automatically the moment you arrive.",
  code: { c: "// Not native to C", python: "class Car:\n    def __init__(self, brand):\n        self.brand = brand  # constructor", javascript: "class Car {\n  constructor(brand) {\n    this.brand = brand;\n  }\n}" },
  application: "Ensures every object starts in a valid, ready-to-use state — like a database connection opening cleanly.",
},
{
  id: "interfaces", tier: 5, title: "Interfaces & Abstract Classes",
  difficulty: "Hard", viz: "class-diagram",
  history: "Java (1995) popularized formal interfaces to let unrelated classes promise to support the same set of behaviors, enabling flexible, swappable components.",
  definition: "A contract that defines what methods a class must implement, without specifying how — enforcing consistency across unrelated classes.",
  analogy: "A job description lists required skills (the interface) — it doesn't dictate exactly how each employee does their job.",
  code: { c: "// Not native to C", python: "from abc import ABC, abstractmethod\nclass Payable(ABC):\n    @abstractmethod\n    def pay(self): pass", javascript: "// JS simulates via duck-typing / TypeScript\ninterface Payable { pay(): void; }" },
  application: "Payment systems define a `Payable` interface so Credit Card, UPI, and Wallet classes can all be used interchangeably.",
},

// ---------------- TIER 6 — DSA ----------------
{
  id: "big-o", tier: 6, title: "Time & Space Complexity (Big-O)",
  difficulty: "Hard", viz: "growth-chart",
  history: "Big-O notation was borrowed from 19th-century mathematics and formalized for computing by Donald Knuth in the 1970s, to compare algorithm efficiency independent of hardware speed.",
  definition: "Big-O describes how an algorithm's running time or memory use grows as input size grows — O(1) constant, O(log n), O(n), O(n log n), O(n²), and worse.",
  analogy: "Judging how a recipe scales — doubling guests might just double prep time (O(n)), or it might make things far messier if every guest needs to meet every other guest (O(n²)).",
  code: { c: "// O(n): one loop through array\nfor (int i = 0; i < n; i++) { ... }", python: "# O(n^2): nested loop\nfor i in range(n):\n    for j in range(n):\n        ...", javascript: "// O(log n): binary search halves\n// the search space each step" },
  application: "Determines whether your app stays fast with 100 users or crawls to a halt with 1 million.",
},
{
  id: "linked-list", tier: 6, title: "Linked Lists",
  difficulty: "Hard", viz: "linked-list",
  history: "Developed in 1955–56 at RAND Corporation for early AI research (the IPL language), because arrays couldn't grow or shrink efficiently as data changed.",
  definition: "A linear structure where each element ('node') holds data plus a pointer to the next node — unlike arrays, nodes aren't stored contiguously.",
  analogy: "A treasure hunt — each clue (node) tells you the data and where to find the next clue, rather than all clues sitting in one drawer.",
  code: { c: "struct Node {\n  int data;\n  struct Node* next;\n};", python: "class Node:\n    def __init__(self, data):\n        self.data = data\n        self.next = None", javascript: "class Node {\n  constructor(data) {\n    this.data = data;\n    this.next = null;\n  }\n}" },
  application: "Used in music playlists ('next song'), browser history (back/forward), and underlying many other data structures.",
},
{
  id: "stacks", tier: 6, title: "Stacks",
  difficulty: "Hard", viz: "stack",
  history: "Introduced in the late 1950s to manage function calls and expression evaluation — the 'call stack' concept is still fundamental to how every program runs today.",
  definition: "A Last-In-First-Out (LIFO) structure — the last item added is the first one removed. Core operations: push (add) and pop (remove).",
  analogy: "A stack of plates — you always add to the top and take from the top; the bottom plate stays put until everything above it is gone.",
  code: { c: "int stack[100], top = -1;\nstack[++top] = 10; // push\nint x = stack[top--]; // pop", python: "stack = []\nstack.append(10)  # push\nx = stack.pop()   # pop", javascript: "let stack = [];\nstack.push(10);\nlet x = stack.pop();" },
  application: "Undo/redo features, browser back button, and how function calls track their return points.",
},
{
  id: "queues", tier: 6, title: "Queues",
  difficulty: "Hard", viz: "queue",
  history: "Modeled directly on real-world waiting lines, queues became essential for early operating systems needing to schedule tasks fairly, in the order they arrived.",
  definition: "A First-In-First-Out (FIFO) structure — the first item added is the first one removed. Core operations: enqueue (add) and dequeue (remove).",
  analogy: "A line at a ticket counter — whoever joined first gets served first.",
  code: { c: "// Simplified with array + front/rear indices\nqueue[rear++] = 10; // enqueue\nint x = queue[front++]; // dequeue", python: "from collections import deque\nq = deque()\nq.append(10)     # enqueue\nx = q.popleft()  # dequeue", javascript: "let queue = [];\nqueue.push(10);      // enqueue\nlet x = queue.shift(); // dequeue" },
  application: "Task scheduling, print job queues, and handling requests in the order they arrive on a server.",
},
{
  id: "trees", tier: 6, title: "Trees (Binary Trees & BST)",
  difficulty: "Hard", viz: "binary-tree",
  history: "Tree structures grew out of 1960s research into hierarchical file systems and compilers, where data naturally branches rather than sitting in a flat line.",
  definition: "A hierarchical structure where each node has a parent and (in a binary tree) up to two children. A Binary Search Tree (BST) keeps left children smaller and right children larger for fast searching.",
  analogy: "A family tree — one root ancestor, branching down into children and grandchildren.",
  code: { c: "struct Node {\n  int data;\n  struct Node *left, *right;\n};", python: "class Node:\n    def __init__(self, data):\n        self.data = data\n        self.left = self.right = None", javascript: "class Node {\n  constructor(data) {\n    this.data = data;\n    this.left = this.right = null;\n  }\n}" },
  application: "File systems, org charts, and database indexes all use tree structures for fast lookups.",
},
{
  id: "graphs", tier: 6, title: "Graphs (BFS/DFS)",
  difficulty: "Hard", viz: "graph",
  history: "Rooted in 18th-century mathematician Euler's solution to the Königsberg bridge problem — the birth of graph theory, later adapted for networks and computing.",
  definition: "A structure of nodes ('vertices') connected by edges, which can be directed or weighted. BFS explores level by level; DFS explores as deep as possible before backtracking.",
  analogy: "A map of cities connected by roads — vertices are cities, edges are the roads between them.",
  code: { c: "// Adjacency list representation\nint adj[100][100]; // simplified", python: "graph = {\"A\": [\"B\", \"C\"], \"B\": [\"D\"]}\n# BFS/DFS traverse this dictionary", javascript: "let graph = { A: [\"B\",\"C\"], B: [\"D\"] };" },
  application: "GPS navigation, social network 'friends of friends', and recommendation systems all rely on graphs.",
},
{
  id: "hashing", tier: 6, title: "Hashing & Hash Maps",
  difficulty: "Hard", viz: "hash-buckets",
  history: "Hashing emerged at IBM in the 1950s to enable near-instant data lookup, without having to scan every record one by one.",
  definition: "A hash function converts a key into an index in an array (a 'bucket'), allowing average O(1) lookup, insertion, and deletion.",
  analogy: "A library that assigns each book a specific shelf based on its title's first letter — you go straight to the shelf instead of checking every book.",
  code: { c: "// Manual hash table implementation needed", python: "cache = {}\ncache[\"jay\"] = 95   # O(1) insert\nprint(cache[\"jay\"]) # O(1) lookup", javascript: "let cache = {};\ncache[\"jay\"] = 95;\nconsole.log(cache[\"jay\"]);" },
  application: "Powers dictionaries/objects in every language, database indexing, and caching systems.",
},
{
  id: "sorting", tier: 6, title: "Sorting Algorithms",
  difficulty: "Hard", viz: "sorting-bars",
  history: "Bubble sort dates to the 1950s as an intuitive first approach; Quicksort (Tony Hoare, 1959) and Merge Sort (John von Neumann, 1945) later proved far faster for large datasets.",
  definition: "Algorithms that arrange data in a specific order. Simple ones (Bubble, Selection) run in O(n²); efficient ones (Merge, Quick) run in O(n log n).",
  analogy: "Sorting a hand of playing cards — bubble sort repeatedly swaps neighbors, while merge sort splits the hand in half, sorts each half, then merges them back.",
  code: { c: "// Bubble sort\nfor (int i=0;i<n-1;i++)\n  for (int j=0;j<n-i-1;j++)\n    if (arr[j]>arr[j+1]) swap(arr[j],arr[j+1]);", python: "arr.sort()  # Python's built-in (Timsort)\n# O(n log n) under the hood", javascript: "arr.sort((a,b) => a - b); // built-in sort" },
  application: "Ranking search results, sorting products by price, and leaderboard rankings.",
},
{
  id: "searching", tier: 6, title: "Searching Algorithms",
  difficulty: "Hard", viz: "binary-search",
  history: "Binary search formalized in the 1940s–60s solved a simple problem: scanning every item (linear search) is far too slow once data grows to millions of entries.",
  definition: "Linear search checks each item one by one — O(n). Binary search repeatedly halves a sorted array to find a target in O(log n).",
  analogy: "Looking up a word in a physical dictionary — you don't start at page 1; you jump to the middle and narrow down, just like binary search.",
  code: { c: "int low=0, high=n-1;\nwhile (low <= high) {\n  int mid = (low+high)/2;\n  if (arr[mid]==target) return mid;\n  else if (arr[mid]<target) low=mid+1;\n  else high=mid-1;\n}", python: "import bisect\nindex = bisect.bisect_left(arr, target)", javascript: "// Binary search on sorted array\nlet low=0, high=arr.length-1;" },
  application: "Autocomplete suggestions, database queries, and any lookup on large sorted datasets.",
},
{
  id: "backtracking", tier: 6, title: "Recursion & Backtracking",
  difficulty: "Hard", viz: "call-stack",
  history: "Formalized through classic puzzles like the Eight Queens problem in the 1960s — a technique for exploring all possibilities and 'undoing' choices that don't work out.",
  definition: "Backtracking builds a solution step by step, and abandons ('backtracks') a path as soon as it's clear it won't lead to a valid answer.",
  analogy: "Navigating a maze — you try a path, and if it's a dead end, you walk back to the last junction and try a different direction.",
  code: { c: "// N-Queens style logic:\n// place -> recurse -> if invalid, undo", python: "def solve(board, row):\n    if row == N:\n        return True\n    for col in range(N):\n        if is_valid(board, row, col):\n            place(board, row, col)\n            if solve(board, row+1):\n                return True\n            remove(board, row, col)  # backtrack", javascript: "// Same pattern: try, recurse, undo if it fails" },
  application: "Sudoku solvers, maze-solving robots, and generating all possible valid combinations (like passwords).",
},
{
  id: "dynamic-programming", tier: 6, title: "Dynamic Programming",
  difficulty: "Hard", viz: "dp-table",
  history: "Coined by Richard Bellman in the 1950s, who needed a technique to break large optimization problems into overlapping smaller ones and avoid re-solving them.",
  definition: "An optimization technique that solves a problem by breaking it into overlapping subproblems, storing ('memoizing') each result so it's never recalculated.",
  analogy: "Instead of re-deriving 2+2 every single time it appears in a huge calculation, you write the answer on a sticky note once and reuse it.",
  code: { c: "int memo[100];\nint fib(int n) {\n  if (n<=1) return n;\n  if (memo[n]) return memo[n];\n  return memo[n] = fib(n-1)+fib(n-2);\n}", python: "from functools import lru_cache\n@lru_cache\ndef fib(n):\n    if n <= 1: return n\n    return fib(n-1) + fib(n-2)", javascript: "let memo = {};\nfunction fib(n) {\n  if (n <= 1) return n;\n  if (memo[n]) return memo[n];\n  return memo[n] = fib(n-1) + fib(n-2);\n}" },
  application: "Route optimization, stock trading strategies, and DNA sequence comparison all rely on DP.",
},
{
  id: "greedy", tier: 6, title: "Greedy Algorithms",
  difficulty: "Hard", viz: "greedy",
  history: "Formalized as a technique in the 1960s–70s, greedy algorithms trade the guarantee of a perfect answer for speed — pick the best option right now, and never look back.",
  definition: "An algorithm that makes the locally optimal choice at each step, hoping it leads to a globally optimal solution — fast, but not always correct for every problem.",
  analogy: "Making change with the fewest coins by always picking the largest coin that fits — usually works, but not in every currency system.",
  code: { c: "// Coin change greedy (works for standard coins)\nwhile (amount > 0) {\n  pick largest coin <= amount;\n  amount -= coin;\n}", python: "coins = [25, 10, 5, 1]\nfor c in coins:\n    while amount >= c:\n        amount -= c\n        count += 1", javascript: "// Same greedy pattern: take biggest\n// valid piece first, repeat" },
  application: "Huffman compression, scheduling the maximum number of meetings, and network routing protocols.",
},

// ---------------- TIER 7 — ADVANCED ----------------
{
  id: "exception-handling", tier: 7, title: "Exception Handling",
  difficulty: "Hard", viz: "try-catch",
  history: "Early programs simply crashed on errors. Languages like CLU and Ada (1970s) introduced structured error handling so programs could fail gracefully instead of dying outright.",
  definition: "A mechanism (try/catch/finally) to detect and respond to runtime errors without crashing the whole program.",
  analogy: "A safety net under a tightrope walker — if something goes wrong, you're caught instead of falling all the way down.",
  code: { c: "// C uses manual error codes,\n// no built-in try/catch", python: "try:\n    result = 10 / 0\nexcept ZeroDivisionError:\n    print(\"Can't divide by zero\")", javascript: "try {\n  JSON.parse(\"invalid\");\n} catch (err) {\n  console.log(\"Parse failed:\", err.message);\n}" },
  application: "Handling network failures, invalid user input, and file-not-found errors without the app crashing.",
},
{
  id: "file-handling", tier: 7, title: "File Handling / I/O",
  difficulty: "Medium", viz: "io-flow",
  history: "As programs needed to save data beyond a single run, file I/O operations became a standard part of every language, letting data persist after the program closes.",
  definition: "Reading data from, and writing data to, files stored on disk — allowing programs to persist information between runs.",
  analogy: "A notebook you can write in and close, then reopen later and still find your notes exactly as you left them.",
  code: { c: "FILE *f = fopen(\"data.txt\", \"w\");\nfprintf(f, \"Hello\");\nfclose(f);", python: "with open(\"data.txt\", \"w\") as f:\n    f.write(\"Hello\")", javascript: "const fs = require('fs');\nfs.writeFileSync('data.txt', 'Hello');" },
  application: "Saving user settings, exporting reports, and loading configuration files at startup.",
},
{
  id: "multithreading", tier: 7, title: "Multithreading & Concurrency",
  difficulty: "Hard", viz: "threads",
  history: "As CPUs gained multiple cores in the 2000s, languages needed ways to run tasks in parallel — a major shift from decades of purely sequential execution.",
  definition: "Running multiple sequences of instructions ('threads') at the same time, sharing the same program's memory space.",
  analogy: "A kitchen with several chefs working simultaneously on different dishes, sharing the same fridge and counters.",
  code: { c: "pthread_t t1;\npthread_create(&t1, NULL, task, NULL);", python: "import threading\nt = threading.Thread(target=task)\nt.start()", javascript: "// JS uses async instead of true threads\n// (Web Workers for real parallelism)" },
  application: "Keeping an app's UI responsive while downloading a file in the background.",
},
{
  id: "memory-management", tier: 7, title: "Memory Management",
  difficulty: "Hard", viz: "memory-stack-heap",
  history: "Early languages required manual memory management (C's malloc/free). Java (1995) popularized automatic 'garbage collection' to reduce memory leaks and crashes.",
  definition: "How a program allocates and frees memory. The 'stack' holds short-lived local variables; the 'heap' holds dynamically-sized data. Garbage collection auto-frees unused heap memory.",
  analogy: "The stack is a small desk you clear the moment a task ends. The heap is a warehouse — items stay until someone deliberately removes them (or a cleanup crew notices they're unused).",
  code: { c: "int *p = malloc(sizeof(int) * 10);\n// ... use it ...\nfree(p); // must free manually!", python: "# Python's garbage collector handles\n# this automatically — no manual free", javascript: "// JS garbage collector reclaims memory\n// automatically when objects are unreachable" },
  application: "Prevents memory leaks in long-running apps like servers, games, and operating systems.",
},
{
  id: "design-patterns", tier: 7, title: "Design Patterns",
  difficulty: "Hard", viz: "class-diagram",
  history: "Catalogued in the influential 1994 'Gang of Four' book, design patterns captured proven solutions to recurring software design problems.",
  definition: "Reusable, named solutions to common software design problems — like Singleton (one instance only), Factory (object creation logic), and Observer (notify subscribers on change).",
  analogy: "Architectural blueprints reused across buildings — you don't reinvent how to build a staircase every time.",
  code: { c: "// Singleton via static variable\nstatic MyStruct* instance = NULL;", python: "class Singleton:\n    _instance = None\n    def __new__(cls):\n        if cls._instance is None:\n            cls._instance = super().__new__(cls)\n        return cls._instance", javascript: "class Singleton {\n  static instance;\n  static getInstance() {\n    if (!this.instance) this.instance = new Singleton();\n    return this.instance;\n  }\n}" },
  application: "Frameworks like React (Observer pattern for state) and database connections (Singleton) use these daily.",
},
{
  id: "generics", tier: 7, title: "Generics / Templates",
  difficulty: "Hard", viz: "generics",
  history: "C++ templates (1990s) and Java generics (2004) let one function or class work with multiple data types safely, without duplicating code for each type.",
  definition: "Writing code that works with any data type, specified as a parameter, while still catching type errors at compile time.",
  analogy: "A universal phone charger case that fits many phone models, instead of buying a separate case per model.",
  code: { c: "// C uses void* or macros to simulate this", python: "from typing import TypeVar, List\nT = TypeVar('T')\ndef first(items: List[T]) -> T:\n    return items[0]", javascript: "// TypeScript generics:\nfunction first<T>(items: T[]): T {\n  return items[0];\n}" },
  application: "Type-safe collections in Java/C++ (like `List<Integer>`) and reusable UI components in TypeScript.",
},
{
  id: "functional-programming", tier: 7, title: "Functional Programming",
  difficulty: "Hard", viz: "pipeline",
  history: "Rooted in 1930s Lambda Calculus (Alonzo Church), popularized by Lisp (1958) and later mainstreamed through JavaScript, Python, and dedicated languages like Haskell.",
  definition: "A style where functions are treated as first-class values — passed around, returned from other functions — favoring pure, side-effect-free functions and immutability.",
  analogy: "An assembly line of pure transformations — each machine takes an input and produces an output without secretly altering anything else on the line.",
  code: { c: "// Function pointers simulate this,\n// but C isn't functional by design", python: "nums = [1, 2, 3, 4]\nsquared = list(map(lambda x: x**2, nums))\nevens = list(filter(lambda x: x%2==0, nums))", javascript: "let nums = [1, 2, 3, 4];\nlet squared = nums.map(x => x ** 2);\nlet evens = nums.filter(x => x % 2 === 0);" },
  application: "Data transformation pipelines, React's rendering model, and big-data processing frameworks.",
},
{
  id: "async-programming", tier: 7, title: "Asynchronous Programming",
  difficulty: "Hard", viz: "async-timeline",
  history: "As web apps needed to fetch data without freezing the page, callbacks emerged first, followed by Promises (2015) and async/await to make async code readable like normal code.",
  definition: "Writing code that can start a long-running task (like a network call) and continue with other work while waiting for it to finish, instead of blocking everything.",
  analogy: "Ordering food at a restaurant — you place the order and continue chatting, instead of standing frozen at the counter until it's ready.",
  code: { c: "// C requires manual thread/callback setup", python: "import asyncio\nasync def fetch_data():\n    await asyncio.sleep(1)\n    return \"data\"", javascript: "async function fetchData() {\n  let res = await fetch('/api/data');\n  return res.json();\n}" },
  application: "Every app that loads data from the internet without freezing — feeds, chats, live dashboards.",
},

// ---------------- TIER 8 — SYSTEMS & APPLIED ----------------
{
  id: "databases-sql", tier: 8, title: "Databases & SQL",
  difficulty: "Medium", viz: "database-table",
  history: "Edgar Codd's 1970 relational model paper introduced storing data in tables with rows/columns, replacing rigid earlier file-based systems — SQL followed shortly after as its query language.",
  definition: "A database stores structured data persistently. SQL (Structured Query Language) is used to create, read, update, and delete that data.",
  analogy: "A digital filing cabinet with labeled folders (tables) and a precise way to ask for exactly the papers you need (queries).",
  code: { c: "// C connects to DBs via libraries\n// like SQLite's C API", python: "import sqlite3\nconn = sqlite3.connect(\"app.db\")\nconn.execute(\"SELECT * FROM users\")", javascript: "// SQL query example:\nSELECT name, age FROM users WHERE age > 18;" },
  application: "Every app storing user accounts, orders, or posts — Instagram, banking apps, e-commerce — relies on databases.",
},
{
  id: "apis-rest", tier: 8, title: "APIs & REST",
  difficulty: "Medium", viz: "api-flow",
  history: "REST was defined by Roy Fielding in his 2000 doctoral thesis, proposing a simple, standardized way for different systems to talk to each other over the web.",
  definition: "An API (Application Programming Interface) lets two programs communicate. REST APIs use standard HTTP methods (GET, POST, PUT, DELETE) over URLs to exchange data, often as JSON.",
  analogy: "A restaurant menu — you (the client) order by name from the menu (API) without needing to know how the kitchen (server) actually cooks it.",
  code: { c: "// Typically uses libcurl for HTTP requests", python: "import requests\nres = requests.get(\"https://api.example.com/users\")\nprint(res.json())", javascript: "fetch(\"https://api.example.com/users\")\n  .then(res => res.json())\n  .then(data => console.log(data));" },
  application: "Every app that talks to a server — weather apps, payment gateways, social media feeds.",
},
{
  id: "version-control", tier: 8, title: "Version Control (Git)",
  difficulty: "Medium", viz: "git-branches",
  history: "Linus Torvalds created Git in 2005 after needing a fast, distributed way to manage the massive, collaborative Linux kernel codebase.",
  definition: "A system that tracks changes to code over time, letting multiple people collaborate, branch off to experiment, and merge work back safely.",
  analogy: "A save-game system for your entire project — you can always roll back to an earlier checkpoint if something breaks.",
  code: { c: "git init\ngit add .\ngit commit -m \"Initial commit\"", python: "git checkout -b new-feature\n# work, then:\ngit merge new-feature", javascript: "git push origin main\ngit pull origin main" },
  application: "Used by virtually every software team on Earth to collaborate on code without overwriting each other's work.",
},
{
  id: "testing-debugging", tier: 8, title: "Testing & Debugging",
  difficulty: "Medium", viz: "test-pass-fail",
  history: "The term 'bug' famously traces to a moth found in the Harvard Mark II in 1947. Formal automated testing practices grew through the 1990s–2000s as codebases became too large to check by hand.",
  definition: "Testing verifies code behaves as expected (often automatically). Debugging is the process of finding and fixing the root cause of unexpected behavior.",
  analogy: "Testing is a quality-control checklist before shipping a product. Debugging is detective work — following clues (errors, logs) back to the culprit.",
  code: { c: "assert(add(2,3) == 5);", python: "def test_add():\n    assert add(2, 3) == 5\n\n# run with: pytest", javascript: "console.assert(add(2, 3) === 5, \"add failed\");" },
  application: "Prevents shipping broken features — every serious codebase has an automated test suite.",
},
{
  id: "networking-basics", tier: 8, title: "Networking Basics",
  difficulty: "Medium", viz: "network-packets",
  history: "The internet's foundation, TCP/IP, was standardized in 1983, defining how data is broken into packets and reliably delivered across interconnected networks.",
  definition: "How computers communicate over networks: data is broken into packets, addressed (IP), and reliably delivered (TCP), often carried by protocols like HTTP for the web.",
  analogy: "Mailing a letter — it's broken into an envelope with an address (IP), sent through the postal system (network), and confirmed delivered (TCP).",
  code: { c: "// Sockets API used for raw networking\nsocket(AF_INET, SOCK_STREAM, 0);", python: "import socket\ns = socket.socket()\ns.connect((\"example.com\", 80))", javascript: "// Browsers abstract this via fetch()\nfetch(\"https://example.com\");" },
  application: "Every web request, video call, and online game relies on these core networking principles.",
},
{
  id: "security-basics", tier: 8, title: "Security Basics",
  difficulty: "Hard", viz: "lock-shield",
  history: "As software began handling money and personal data, historical breaches (like the 1988 Morris Worm) proved security couldn't be an afterthought — it had to be built in from the start.",
  definition: "Practices to protect software from misuse: validating all input, hashing passwords instead of storing them plainly, and encrypting sensitive data in transit and at rest.",
  analogy: "Locking your house, not leaving spare keys under the mat, and shredding sensitive documents before throwing them away.",
  code: { c: "// Never trust raw input — always validate\n// buffer lengths to avoid overflow bugs", python: "import bcrypt\nhashed = bcrypt.hashpw(b\"mypassword\", bcrypt.gensalt())", javascript: "// Never do: eval(userInput)\n// Always validate/sanitize user input" },
  application: "Protects login systems, payment data, and personal information from being stolen or misused.",
},

// ---------------- TIER 9 — SPECIALIZATION BRIDGES ----------------
{
  id: "web-dev-concepts", tier: 9, title: "Web Development Concepts",
  difficulty: "Medium", viz: "client-server",
  history: "Tim Berners-Lee invented the Web in 1989 as a way to link documents. It evolved from static pages into today's dynamic, interactive client-server applications.",
  definition: "The client (browser) requests pages/data from a server. The DOM (Document Object Model) represents the page structure that JavaScript can dynamically update.",
  analogy: "A restaurant: the client is the customer ordering, the server is the kitchen preparing and sending back the response.",
  code: { c: "// Not typically used for web front-ends", python: "# Backend (Flask example)\n@app.route(\"/\")\ndef home():\n    return \"Hello, Web!\"", javascript: "document.getElementById(\"title\")\n  .textContent = \"Hello, DOM!\";" },
  application: "Every website you use — from search engines to social media — is built on these client-server principles.",
},
{
  id: "mobile-dev-basics", tier: 9, title: "Mobile Development Basics",
  difficulty: "Medium", viz: "mobile-screen",
  history: "The 2008 launch of the iOS App Store and Android Market created an entirely new industry built around apps designed for touch, small screens, and limited battery/data.",
  definition: "Building apps for phones/tablets — natively (Swift for iOS, Kotlin for Android) or cross-platform (Flutter, React Native) — with attention to touch UI and device resources.",
  analogy: "Designing a tool that must work perfectly whether it's held in one hand, dropped in a pocket, or used with patchy internet.",
  code: { c: "// Rarely used directly for mobile UI", python: "# Kivy example (cross-platform)\nfrom kivy.app import App", javascript: "// React Native example\nfunction App() {\n  return <Text>Hello Mobile!</Text>;\n}" },
  application: "The apps you use daily on your phone — banking, messaging, maps — all come from this specialization.",
},
{
  id: "ai-ml-foundations", tier: 9, title: "AI/ML Foundations",
  difficulty: "Hard", viz: "neural-network",
  history: "The term 'Artificial Intelligence' was coined at a 1956 Dartmouth workshop. Decades of slow progress gave way to a breakthrough era after 2012, when deep neural networks began outperforming older methods.",
  definition: "Machine Learning lets a program improve at a task by learning patterns from data, rather than being explicitly programmed with fixed rules.",
  analogy: "Teaching by example rather than by rulebook — showing thousands of cat photos until the system recognizes cats on its own.",
  code: { c: "// Rarely used directly for ML modeling", python: "from sklearn.linear_model import LinearRegression\nmodel = LinearRegression()\nmodel.fit(X_train, y_train)", javascript: "// TensorFlow.js example\nconst model = tf.sequential();" },
  application: "Powers recommendation systems, spam filters, voice assistants, and image recognition — directly relevant to your interest in AI/ML.",
},
{
  id: "iot-basics", tier: 9, title: "IoT Basics",
  difficulty: "Hard", viz: "iot-devices",
  history: "The term 'Internet of Things' was coined in 1999, but only became practical after cheap microcontrollers (Arduino, 2005) and Wi-Fi chips made connecting everyday objects affordable.",
  definition: "IoT connects physical devices (sensors, appliances) to the internet, letting them collect data and be controlled remotely — usually via microcontrollers running lightweight code.",
  analogy: "Giving everyday objects a voice and a set of ears — a thermostat that can 'hear' your phone's command and 'speak' back its current reading.",
  code: { c: "// Arduino (C-based)\nvoid loop() {\n  int val = analogRead(A0);\n  Serial.println(val);\n}", python: "# MicroPython on ESP32\nimport machine\nsensor = machine.ADC(machine.Pin(34))", javascript: "// Node-RED / Johnny-Five for IoT\nboard.on(\"ready\", () => { ... });" },
  application: "Smart home devices, wearable fitness trackers, and industrial sensors — directly relevant to your interest in IoT.",
},
];
